### ISSUE TITLE
How to make table grid for dropping ui here?

### ISSUE THREAD

**Issue by ivanatorr** [LuisMPS/build-ui#3]
I'm trying to make it so that I can take a table layout and drag elements there, but I have duplicate elements in all columns, how can I fix this?

**Comment by ivanatorr** [comment]
https://drive.google.com/file/d/1eFQt_lG_VMFqyaqa01jkQX6_HrFWo7ee/view?usp=drivesdk . There is a video how working my app and how looks my issue. https://github.com/ivanatorr/practice-institute it is my repository with code. You can check this. I'm new in react and I was given the task to write a site builder if you can help me with this problem, I will be very happy thank you)

**Comment by LuisMPS** [comment]
Hi, thanks. Could you please change the video settings to make it public?

**Comment by ivanatorr** [comment]
Change it, sorry

**Comment by LuisMPS** [comment]
I am looking into it. As soon as I figure out what is happening, I will let you know.

**Comment by ivanatorr** [comment]
Ok, thank you

**Comment by LuisMPS** [comment]
Hi!
Yes, it is possible. The cleanest approach would be to code a set of preview components, in the same way as normal view components (just a lot simpler because you usually will only want to render the end components) and use these in the view object you would pass down to the Workspace component. You could choose to render the preview using the same Workspace that you are using to build the site and toggle the view prop somehow, or elsewhere with a different Workspace component.

**Comment by LuisMPS** [comment]
I see. I would recommend having that data as a part of the component's props in the build-ui tree instead of having it in the component's state. I checked, for example, what InputView looks like and you would need to save "label" and "type" as a part of the component's props. I can do an example for you and open a PR as last time, and then you can do the rest.

**Comment by LuisMPS** [comment]
Would you like having that code example on a PR?

**Comment by ivanatorr** [comment]
I have done fresh commit

**Comment by LuisMPS** [comment]
Hi, I changed some code in your InputTools and InputView components. The code for the rest of components should be very similiar. I did not change anything in the preview code, it looks like it is going in a good direction, only remember to use different view components when you have those ready (so no more moving around / website edition is allowed).

**Comment by ivanatorr** [comment]
Hi, how did you use this "onDragEnter = {editor.handlePaintDropZone}
        onDragLeave = {editor.handleEraseDropZone}" i want to add highlighting when i hover dragged element on section, and all elements in section now undraggble, i dont know why, you can check repo, if you want

**Comment by LuisMPS** [comment]
Those couple of functions editor.handlePaintDropZone and editor.handleEraseDropZone are not part of build-ui's interface. I think you got that from the demo code, and if you notice, I am not directly importing useEditor from build-ui, but instead from a wrapper hook called useDemoEditor, which you can also find the source code for in that same project. https://github.com/LuisMPS/build-ui/blob/main/examples/demo/src/hooks/useDemoEditor.js

**Comment by ivanatorr** [comment]
Thank you)

**Comment by LuisMPS** [comment]
Hi ivanatorr, thanks for your questions. I'll close this now.
