### ISSUE TITLE
TailwindCss?

### ISSUE THREAD

**Issue by tonmaz** [LuisMPS/build-ui#4]
Your demo project is great!!! It uses material-ui a lot.
I normally use tailwindcss. I am wondering how it would be like to create the same project as your Demo using tailwindcss. Is it possible with all those features? More difficult? How would be the developer experience?

**Comment by LuisMPS** [comment]
Hi tonmaz,
Thanks for your comment on the demo.

To be honest, I have never used Tailwind for styling. I was just going through the documentation, and I am pretty sure that Tailwind and build-ui can be used together, so no worries about that. 

Yes, I think you can replicate all features in the demo using Tailwind, maybe with a different approach since Tailwind works mostly by adding class names to have some styles whereas Material UI uses already-styled React Components. As for what the developer experience would be like, I guess it is just similar as what it would be like in any other project using Tailwing. build-ui doesn't make using Tailwind any harder or any easier. 

Maybe you can try and let me know afterwards you if you have any questions.

**Comment by LuisMPS** [comment]
Hi tonmaz, I'll close this issue. Hope your question was answered.
